version: "3"

services:
  anonimowediscowyznania:
    container_name: anonimowediscowyznania
    build:
      context: ./
      dockerfile: Dockerfile
    command: python main.py
    restart: unless-stopped
    volumes:
      - .:/code